dist: trusty
sudo: false

language: go
go:
  - "1.7.x"
  - "1.8.x"
  - "1.9.x"
  - "1.10.x"
  - "tip"

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover

# Only install and run the tests for the current directory
# This avoids testing the demo directory (which has no tests) and
# depends on packages that only support Go 1.9+.
install:
  - go get -t -v .

script:
  - travis_retry $HOME/gopath/bin/goveralls -service=travis-ci -package .
